{{- if .Values.github.token }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ranking-service.fullname" . }}
  labels:
    {{- include "ranking-service.labels" . | nindent 4 }}
type: Opaque
stringData:
  GITHUB_TOKEN: {{ .Values.github.token | quote }}
{{- end }}
